### ISSUE TITLE
Hypixel API Abuse

### ISSUE THREAD

**Issue by SoCuul** [GoogleSites/hypixel-api#1]
The multi API key feature is API bannable btw.

**Comment by GoogleSites** [comment]
> The multi API key feature is API bannable btw.

It's only bannable if you use them to abuse. If you're hosting something that legitimately uses up the requests (up to 3 keys), then it's fine

**Comment by SoCuul** [comment]
But the really only use for multi API keys is to bypass the cool down.

**Comment by GoogleSites** [comment]
You're allowed to use multiple keys if you reach it without abusing (eg. you can't scrape the entire playerlist with 20 keys, but you can use 2-3 keys on a public website/Discord bot)

**Comment by SoCuul** [comment]
![image](https://user-images.githubusercontent.com/63339559/117031685-aefff480-acb5-11eb-872f-a110d7ed5e18.jpeg)
That's not what I see Atleast
