### ISSUE TITLE
incorrect type definition for Auction

### ISSUE THREAD

**Issue by istanbul-not-constantinople** [GoogleSites/hypixel-api#2]
in `typing/types.d.ts`, `Auction.item_bytes` is defined as `HypixelBinaryData`, which is an interface of two properties. it is, in fact just a string.

![image](https://user-images.githubusercontent.com/67161944/120789423-8031a400-c529-11eb-8999-8a7a8a1aaef1.png)

not a big issue. just a mistake, and a wierd one at that.

**Comment by GoogleSites** [comment]
Fixed in version `1.2.24`, thanks!
