### ISSUE TITLE
/recentgames tntgames tnttag does not match the name in stats

### ISSUE THREAD

**Issue by a1cd** [GoogleSites/hypixel-api#3]
after a player plays tnt tag (or _tntag_), the record shows 
```json
{date: [timestamp], gameType: 'TNTGAMES', mode: 'TNTTAG', map: [map]}
```
This says _TNTTAG_ but in `/player` under TNTgames they spell tnt tag `tntag`. "`wins_tntag`"

It is spelled _tnttag_ in one place and _tntag_ another

using the api would be easier if it was more consistent.

**Comment by GoogleSites** [comment]
This is a wrapper for the Hypixel API, not the API itself. I use the names provided by the API, so any inconsistencies in their naming are reflected here.

Unless there are incorrect typings in the library, this is more of an issue for Hypixel itself.

**Comment by a1cd** [comment]
shoot, sorry... this is awkward. I completely thought i was commenting on the hypixel api. Whoops!
